import { toID } from '@pkmn/data';

import { championsLearnsetsBySpecies } from '@/utils/ChampionsLearnsets';

/**
 * Data for the Pokémon Champions rulesets.
 *
 * Champions is not covered by the Pokémon Showdown data bundled in `@pkmn/dex`, so its legal
 * Pokémon, items and mechanics are declared here and applied on top of the Gen 9 dex.
 *
 * Sources:
 *  - Roster and regulation rules: https://bulbapedia.bulbagarden.net/wiki/Regulation_Set_M-B
 *  - Items: https://www.serebii.net/pokemonchampions/items.shtml
 *  - No IVs: https://nintendoeverything.com/pokemon-champions-wont-have-ivs-developer-explains-why/
 */

/** Every Champions format ID starts with this prefix, which is how the rest of the app detects them. */
export const championsFormatPrefix = 'champions';

export const isChampionsFormatId = (formatId: string): boolean => formatId.startsWith(championsFormatPrefix);

/**
 * Champions treats every Pokémon as having 31 IVs in every stat, so IVs are not a team building
 * decision in these formats.
 */
export const allowsIvCustomization = (formatId: string): boolean => !isChampionsFormatId(formatId);

/**
 * The Regulation Set M-B roster (17 June 2026 - 2 September 2026). No Pokémon is restricted in
 * M-B, so this is also the full Champions roster.
 * Names follow the Pokémon Showdown convention so that they resolve against `@pkmn/dex`.
 */
export const championsRegulationMBSpecies: string[] = [
  'Venusaur',
  'Charizard',
  'Blastoise',
  'Beedrill',
  'Pidgeot',
  'Arbok',
  'Pikachu',
  'Raichu',
  'Raichu-Alola',
  'Clefable',
  'Ninetales',
  'Ninetales-Alola',
  'Vileplume',
  'Arcanine',
  'Arcanine-Hisui',
  'Alakazam',
  'Machamp',
  'Victreebel',
  'Slowbro',
  'Slowbro-Galar',
  'Gengar',
  'Kangaskhan',
  'Starmie',
  'Pinsir',
  'Tauros',
  'Tauros-Paldea-Combat',
  'Tauros-Paldea-Blaze',
  'Tauros-Paldea-Aqua',
  'Gyarados',
  'Ditto',
  'Vaporeon',
  'Jolteon',
  'Flareon',
  'Aerodactyl',
  'Snorlax',
  'Dragonite',
  'Meganium',
  'Typhlosion',
  'Typhlosion-Hisui',
  'Feraligatr',
  'Ariados',
  'Ampharos',
  'Azumarill',
  'Politoed',
  'Espeon',
  'Umbreon',
  'Slowking',
  'Slowking-Galar',
  'Forretress',
  'Steelix',
  'Qwilfish',
  'Scizor',
  'Heracross',
  'Skarmory',
  'Houndoom',
  'Tyranitar',
  'Sceptile',
  'Blaziken',
  'Swampert',
  'Pelipper',
  'Gardevoir',
  'Sableye',
  'Mawile',
  'Aggron',
  'Medicham',
  'Manectric',
  'Sharpedo',
  'Camerupt',
  'Torkoal',
  'Altaria',
  'Milotic',
  'Castform',
  'Banette',
  'Chimecho',
  'Absol',
  'Glalie',
  'Metagross',
  'Torterra',
  'Infernape',
  'Empoleon',
  'Staraptor',
  'Luxray',
  'Roserade',
  'Rampardos',
  'Bastiodon',
  'Lopunny',
  'Spiritomb',
  'Garchomp',
  'Lucario',
  'Hippowdon',
  'Toxicroak',
  'Abomasnow',
  'Weavile',
  'Rhyperior',
  'Leafeon',
  'Glaceon',
  'Gliscor',
  'Mamoswine',
  'Gallade',
  'Froslass',
  'Rotom',
  'Rotom-Heat',
  'Rotom-Wash',
  'Rotom-Frost',
  'Rotom-Fan',
  'Rotom-Mow',
  'Serperior',
  'Emboar',
  'Samurott',
  'Samurott-Hisui',
  'Watchog',
  'Liepard',
  'Simisage',
  'Simisear',
  'Simipour',
  'Musharna',
  'Excadrill',
  'Audino',
  'Conkeldurr',
  'Scolipede',
  'Whimsicott',
  'Krookodile',
  'Scrafty',
  'Cofagrigus',
  'Garbodor',
  'Zoroark',
  'Zoroark-Hisui',
  'Reuniclus',
  'Vanilluxe',
  'Emolga',
  'Eelektross',
  'Chandelure',
  'Beartic',
  'Stunfisk',
  'Stunfisk-Galar',
  'Golurk',
  'Hydreigon',
  'Volcarona',
  'Chesnaught',
  'Delphox',
  'Greninja',
  'Diggersby',
  'Talonflame',
  'Vivillon',
  'Pyroar',
  'Floette',
  'Floette-Eternal',
  'Florges',
  'Pangoro',
  'Furfrou',
  'Meowstic',
  'Meowstic-F',
  'Aegislash',
  'Aromatisse',
  'Slurpuff',
  'Malamar',
  'Barbaracle',
  'Dragalge',
  'Clawitzer',
  'Heliolisk',
  'Tyrantrum',
  'Aurorus',
  'Sylveon',
  'Hawlucha',
  'Dedenne',
  'Goodra',
  'Goodra-Hisui',
  'Klefki',
  'Trevenant',
  'Gourgeist',
  'Gourgeist-Small',
  'Gourgeist-Large',
  'Gourgeist-Super',
  'Avalugg',
  'Avalugg-Hisui',
  'Noivern',
  'Decidueye',
  'Decidueye-Hisui',
  'Incineroar',
  'Primarina',
  'Toucannon',
  'Crabominable',
  'Lycanroc',
  'Lycanroc-Midnight',
  'Lycanroc-Dusk',
  'Toxapex',
  'Mudsdale',
  'Araquanid',
  'Salazzle',
  'Tsareena',
  'Oranguru',
  'Passimian',
  'Mimikyu',
  'Drampa',
  'Kommo-o',
  'Corviknight',
  'Flapple',
  'Appletun',
  'Sandaconda',
  'Polteageist',
  'Hatterene',
  'Grimmsnarl',
  'Mr. Rime',
  'Runerigus',
  'Alcremie',
  'Falinks',
  'Morpeko',
  'Dragapult',
  'Wyrdeer',
  'Kleavor',
  'Basculegion',
  'Basculegion-F',
  'Sneasler',
  'Overqwil',
  'Meowscarada',
  'Skeledirge',
  'Quaquaval',
  'Maushold',
  'Garganacl',
  'Armarouge',
  'Ceruledge',
  'Bellibolt',
  'Scovillain',
  'Espathra',
  'Tinkaton',
  'Palafin',
  'Orthworm',
  'Glimmora',
  'Houndstone',
  'Annihilape',
  'Farigiraf',
  'Kingambit',
  'Gholdengo',
  'Sinistcha',
  'Archaludon',
  'Hydrapple',
];

/** Non-berry, non-Mega Stone held items available in Champions. */
export const championsHeldItems: string[] = [
  'Big Root',
  'Black Belt',
  'Black Glasses',
  'Bright Powder',
  'Charcoal',
  'Choice Scarf',
  'Damp Rock',
  'Dragon Fang',
  'Expert Belt',
  'Fairy Feather',
  'Focus Band',
  'Focus Sash',
  'Hard Stone',
  'Heat Rock',
  'Icy Rock',
  'Iron Ball',
  "King's Rock",
  'Leftovers',
  'Life Orb',
  'Light Ball',
  'Light Clay',
  'Magnet',
  'Mental Herb',
  'Metal Coat',
  'Metronome',
  'Miracle Seed',
  'Muscle Band',
  'Mystic Water',
  'Never-Melt Ice',
  'Poison Barb',
  'Quick Claw',
  'Scope Lens',
  'Sharp Beak',
  'Shed Shell',
  'Shell Bell',
  'Silk Scarf',
  'Silver Powder',
  'Smooth Rock',
  'Soft Sand',
  'Spell Tag',
  'Twisted Spoon',
  'White Herb',
  'Wide Lens',
  'Wise Glasses',
  'Zoom Lens',
];

/** Berries available in Champions. */
export const championsBerries: string[] = [
  'Aspear Berry',
  'Babiri Berry',
  'Charti Berry',
  'Cheri Berry',
  'Chesto Berry',
  'Chilan Berry',
  'Chople Berry',
  'Coba Berry',
  'Colbur Berry',
  'Haban Berry',
  'Kasib Berry',
  'Kebia Berry',
  'Leppa Berry',
  'Lum Berry',
  'Occa Berry',
  'Oran Berry',
  'Passho Berry',
  'Payapa Berry',
  'Pecha Berry',
  'Persim Berry',
  'Rawst Berry',
  'Rindo Berry',
  'Roseli Berry',
  'Shuca Berry',
  'Sitrus Berry',
  'Tanga Berry',
  'Wacan Berry',
  'Yache Berry',
];

/**
 * Every Mega Stone available in Champions: the ones inherited from Gen 6/7 plus the ones Champions
 * introduced. All of them, and the Mega formes they unlock, come from the Showdown data.
 */
export const championsMegaStones: string[] = [
  'Abomasite',
  'Absolite',
  'Aerodactylite',
  'Aggronite',
  'Alakazite',
  'Altarianite',
  'Ampharosite',
  'Audinite',
  'Banettite',
  'Barbaracite',
  'Beedrillite',
  'Blastoisinite',
  'Blazikenite',
  'Cameruptite',
  'Chandelurite',
  'Charizardite X',
  'Charizardite Y',
  'Chesnaughtite',
  'Chimechite',
  'Clefablite',
  'Crabominite',
  'Delphoxite',
  'Dragalgite',
  'Dragoninite',
  'Drampanite',
  'Eelektrossite',
  'Emboarite',
  'Excadrite',
  'Falinksite',
  'Feraligite',
  'Floettite',
  'Froslassite',
  'Galladite',
  'Garchompite',
  'Gardevoirite',
  'Gengarite',
  'Glalitite',
  'Glimmoranite',
  'Golurkite',
  'Greninjite',
  'Gyaradosite',
  'Hawluchanite',
  'Heracronite',
  'Houndoominite',
  'Kangaskhanite',
  'Lopunnite',
  'Lucarionite',
  'Malamarite',
  'Manectite',
  'Mawilite',
  'Medichamite',
  'Meganiumite',
  'Meowsticite',
  'Metagrossite',
  'Pidgeotite',
  'Pinsirite',
  'Pyroarite',
  'Raichunite X',
  'Raichunite Y',
  'Sablenite',
  'Sceptilite',
  'Scizorite',
  'Scolipite',
  'Scovillainite',
  'Scraftinite',
  'Sharpedonite',
  'Skarmorite',
  'Slowbronite',
  'Staraptite',
  'Starminite',
  'Steelixite',
  'Swampertite',
  'Tyranitarite',
  'Venusaurite',
  'Victreebelite',
];

/** Every item a Champions Pokémon may hold. */
export const championsItems: string[] = [...championsHeldItems, ...championsBerries, ...championsMegaStones];

/**
 * Champions replaced EVs with Stat Points: 66 per Pokémon, at most 32 in a single stat, and each
 * point is worth exactly +1 to that stat at level 50. They are stored in, and exported to, the EVs
 * field of a Showdown set, e.g. `EVs: 2 HP / 32 SpA / 32 Spe`.
 */
export const championsMaxTotalStatPoints = 66;

export const championsMaxSingleStatPoints = 32;

/**
 * Every move a Pokémon may use in Champions. Champions carries its own move list rather than Gen 9's:
 * it brings back moves Gen 9 dropped (e.g. Light of Ruin) and leaves out a long tail of older moves,
 * along with everything tied to a mechanic it does not have (Hidden Power, Tera Blast, Z-moves, Max
 * moves). Which of these a given Pokémon actually gets is still decided by its Pokémon Showdown
 * learnset.
 *
 * Source: https://www.serebii.net/pokemonchampions/moves.shtml
 */
export const championsMoves: string[] = [
  'Accelerock',
  'Acid Armor',
  'Acid Spray',
  'Acrobatics',
  'Acupressure',
  'Aerial Ace',
  'After You',
  'Agility',
  'Air Cutter',
  'Air Slash',
  'Alluring Voice',
  'Ally Switch',
  'Amnesia',
  'Ancient Power',
  'Apple Acid',
  'Aqua Cutter',
  'Aqua Jet',
  'Aqua Ring',
  'Aqua Step',
  'Aqua Tail',
  'Armor Cannon',
  'Aromatic Mist',
  'Assurance',
  'Attract',
  'Aura Sphere',
  'Aura Wheel',
  'Aurora Veil',
  'Avalanche',
  'Axe Kick',
  'Baby-Doll Eyes',
  'Baneful Bunker',
  'Barb Barrage',
  'Baton Pass',
  'Beak Blast',
  'Beat Up',
  'Belch',
  'Belly Drum',
  'Bind',
  'Bite',
  'Bitter Blade',
  'Bitter Malice',
  'Blast Burn',
  'Blaze Kick',
  'Blizzard',
  'Block',
  'Body Press',
  'Body Slam',
  'Bone Rush',
  'Boomburst',
  'Bounce',
  'Brave Bird',
  'Breaking Swipe',
  'Brick Break',
  'Brutal Swing',
  'Bug Bite',
  'Bug Buzz',
  'Bulk Up',
  'Bulldoze',
  'Bullet Punch',
  'Bullet Seed',
  'Burn Up',
  'Burning Jealousy',
  'Calm Mind',
  'Ceaseless Edge',
  'Charge',
  'Charge Beam',
  'Charm',
  'Chilling Water',
  'Chilly Reception',
  'Circle Throw',
  'Clanging Scales',
  'Clangorous Soul',
  'Clear Smog',
  'Close Combat',
  'Coaching',
  'Coil',
  'Comeuppance',
  'Confuse Ray',
  'Copycat',
  'Corrosive Gas',
  'Cosmic Power',
  'Cotton Guard',
  'Cotton Spore',
  'Counter',
  'Covet',
  'Crabhammer',
  'Cross Chop',
  'Cross Poison',
  'Crunch',
  'Crush Claw',
  'Curse',
  'Dark Pulse',
  'Darkest Lariat',
  'Dazzling Gleam',
  'Decorate',
  'Defog',
  'Destiny Bond',
  'Detect',
  'Dig',
  'Dire Claw',
  'Disable',
  'Discharge',
  'Dive',
  'Double Hit',
  'Double Team',
  'Double-Edge',
  'Draco Meteor',
  'Dragon Cheer',
  'Dragon Claw',
  'Dragon Dance',
  'Dragon Darts',
  'Dragon Pulse',
  'Dragon Rush',
  'Dragon Tail',
  'Drain Punch',
  'Draining Kiss',
  'Drill Peck',
  'Drill Run',
  'Dual Wingbeat',
  'Dynamic Punch',
  'Earth Power',
  'Earthquake',
  'Eerie Impulse',
  'Eerie Spell',
  'Electric Terrain',
  'Electrify',
  'Electro Ball',
  'Electro Shot',
  'Electroweb',
  'Encore',
  'Endeavor',
  'Endure',
  'Energy Ball',
  'Entrainment',
  'Eruption',
  'Expanding Force',
  'Explosion',
  'Extrasensory',
  'Extreme Speed',
  'Facade',
  'Fairy Lock',
  'Fake Out',
  'Fake Tears',
  'Feather Dance',
  'Feint',
  'Fell Stinger',
  'Fickle Beam',
  'Fiery Dance',
  'Final Gambit',
  'Fire Blast',
  'Fire Fang',
  'Fire Lash',
  'Fire Punch',
  'Fire Spin',
  'First Impression',
  'Fissure',
  'Flail',
  'Flame Charge',
  'Flamethrower',
  'Flare Blitz',
  'Flash Cannon',
  'Flatter',
  'Fling',
  'Flip Turn',
  'Flower Trick',
  'Fly',
  'Flying Press',
  'Focus Blast',
  'Focus Energy',
  'Focus Punch',
  'Follow Me',
  "Forest's Curse",
  'Foul Play',
  'Freeze-Dry',
  'Frenzy Plant',
  'Frost Breath',
  'Future Sight',
  'Gastro Acid',
  'Giga Drain',
  'Giga Impact',
  'Gigaton Hammer',
  'Glare',
  'Grass Knot',
  'Grassy Glide',
  'Grassy Terrain',
  'Grav Apple',
  'Gravity',
  'Growth',
  'Guard Split',
  'Guard Swap',
  'Guillotine',
  'Gunk Shot',
  'Gyro Ball',
  'Hammer Arm',
  'Hard Press',
  'Haze',
  'Head Smash',
  'Headlong Rush',
  'Heal Bell',
  'Heal Pulse',
  'Healing Wish',
  'Heat Crash',
  'Heat Wave',
  'Heavy Slam',
  'Helping Hand',
  'Hex',
  'High Horsepower',
  'High Jump Kick',
  'Horn Drill',
  'Horn Leech',
  'Howl',
  'Hurricane',
  'Hydro Cannon',
  'Hydro Pump',
  'Hyper Beam',
  'Hyper Voice',
  'Hypnosis',
  'Ice Beam',
  'Ice Fang',
  'Ice Hammer',
  'Ice Punch',
  'Ice Shard',
  'Ice Spinner',
  'Icicle Crash',
  'Icicle Spear',
  'Icy Wind',
  'Imprison',
  'Infernal Parade',
  'Inferno',
  'Infestation',
  'Ingrain',
  'Instruct',
  'Iron Defense',
  'Iron Head',
  'Iron Tail',
  'Jet Punch',
  "King's Shield",
  'Knock Off',
  'Kowtow Cleave',
  'Lash Out',
  'Last Resort',
  'Last Respects',
  'Lava Plume',
  'Leaf Blade',
  'Leaf Storm',
  'Leech Life',
  'Leech Seed',
  'Life Dew',
  'Light Screen',
  'Light of Ruin',
  'Liquidation',
  'Lock-On',
  'Low Kick',
  'Low Sweep',
  'Lumina Crash',
  'Lunge',
  'Mach Punch',
  'Magic Powder',
  'Magic Room',
  'Magnet Rise',
  'Magnetic Flux',
  'Make It Rain',
  'Matcha Gotcha',
  'Mean Look',
  'Mega Kick',
  'Megahorn',
  'Memento',
  'Metal Burst',
  'Metal Sound',
  'Meteor Beam',
  'Meteor Mash',
  'Minimize',
  'Mirror Coat',
  'Misty Explosion',
  'Misty Terrain',
  'Moonblast',
  'Moonlight',
  'Morning Sun',
  'Mortal Spin',
  'Mountain Gale',
  'Mud Shot',
  'Mud-Slap',
  'Muddy Water',
  'Mystical Fire',
  'Nasty Plot',
  'Night Daze',
  'Night Shade',
  'Night Slash',
  'No Retreat',
  'Noble Roar',
  'Nuzzle',
  'Outrage',
  'Overheat',
  'Pain Split',
  'Parabolic Charge',
  'Parting Shot',
  'Payback',
  'Perish Song',
  'Petal Blizzard',
  'Petal Dance',
  'Phantom Force',
  'Pin Missile',
  'Play Rough',
  'Pluck',
  'Poison Fang',
  'Poison Jab',
  'Poison Powder',
  'Pollen Puff',
  'Poltergeist',
  'Population Bomb',
  'Pounce',
  'Power Gem',
  'Power Shift',
  'Power Split',
  'Power Swap',
  'Power Trick',
  'Power Trip',
  'Power Whip',
  'Protect',
  'Psych Up',
  'Psychic',
  'Psychic Fangs',
  'Psychic Noise',
  'Psychic Terrain',
  'Psycho Cut',
  'Psyshield Bash',
  'Psyshock',
  'Quash',
  'Quick Attack',
  'Quick Guard',
  'Quiver Dance',
  'Rage Fist',
  'Rage Powder',
  'Raging Bull',
  'Raging Fury',
  'Rain Dance',
  'Rapid Spin',
  'Razor Shell',
  'Recover',
  'Recycle',
  'Reflect',
  'Reflect Type',
  'Rest',
  'Reversal',
  'Rising Voltage',
  'Roar',
  'Rock Blast',
  'Rock Polish',
  'Rock Slide',
  'Rock Tomb',
  'Rock Wrecker',
  'Role Play',
  'Roost',
  'Round',
  'Sacred Sword',
  'Safeguard',
  'Salt Cure',
  'Sand Tomb',
  'Sandstorm',
  'Scald',
  'Scale Shot',
  'Scary Face',
  'Scorching Sands',
  'Screech',
  'Seed Bomb',
  'Seismic Toss',
  'Self-Destruct',
  'Shadow Ball',
  'Shadow Claw',
  'Shadow Punch',
  'Shadow Sneak',
  'Shed Tail',
  'Sheer Cold',
  'Shell Side Arm',
  'Shell Smash',
  'Shelter',
  'Simple Beam',
  'Sing',
  'Skill Swap',
  'Skitter Smack',
  'Sky Attack',
  'Slack Off',
  'Sleep Powder',
  'Sleep Talk',
  'Sludge Bomb',
  'Sludge Wave',
  'Smack Down',
  'Smart Strike',
  'Snap Trap',
  'Snarl',
  'Snore',
  'Snowscape',
  'Soak',
  'Soft-Boiled',
  'Solar Beam',
  'Solar Blade',
  'Sparkling Aria',
  'Speed Swap',
  'Spicy Extract',
  'Spikes',
  'Spiky Shield',
  'Spirit Break',
  'Spirit Shackle',
  'Spit Up',
  'Spite',
  'Spore',
  'Stealth Rock',
  'Steel Beam',
  'Steel Roller',
  'Steel Wing',
  'Sticky Web',
  'Stockpile',
  'Stomping Tantrum',
  'Stone Axe',
  'Stone Edge',
  'Stored Power',
  'Storm Throw',
  'Strength Sap',
  'String Shot',
  'Struggle',
  'Struggle Bug',
  'Stuff Cheeks',
  'Stun Spore',
  'Substitute',
  'Sucker Punch',
  'Sunny Day',
  'Super Fang',
  'Supercell Slam',
  'Superpower',
  'Surf',
  'Swagger',
  'Swallow',
  'Sweet Kiss',
  'Sweet Scent',
  'Switcheroo',
  'Swords Dance',
  'Synthesis',
  'Syrup Bomb',
  'Tail Slap',
  'Tailwind',
  'Taunt',
  'Tearful Look',
  'Teatime',
  'Teeter Dance',
  'Temper Flare',
  'Terrain Pulse',
  'Thief',
  'Thrash',
  'Throat Chop',
  'Thunder',
  'Thunder Fang',
  'Thunder Punch',
  'Thunder Wave',
  'Thunderbolt',
  'Tickle',
  'Tidy Up',
  'Topsy-Turvy',
  'Torch Song',
  'Torment',
  'Toxic',
  'Toxic Spikes',
  'Toxic Thread',
  'Trailblaze',
  'Transform',
  'Tri Attack',
  'Trick',
  'Trick Room',
  'Trick-or-Treat',
  'Triple Arrows',
  'Triple Axel',
  'Trop Kick',
  'Twin Beam',
  'U-turn',
  'Upper Hand',
  'Uproar',
  'Vacuum Wave',
  'Venoshock',
  'Volt Switch',
  'Volt Tackle',
  'Water Pulse',
  'Water Shuriken',
  'Water Spout',
  'Waterfall',
  'Wave Crash',
  'Weather Ball',
  'Whirlpool',
  'Whirlwind',
  'Wide Guard',
  'Wild Charge',
  'Will-O-Wisp',
  'Wish',
  'Wonder Room',
  'Wood Hammer',
  'Worry Seed',
  'Wrap',
  'X-Scissor',
  'Yawn',
  'Zap Cannon',
  'Zen Headbutt',
];

const championsSpeciesIds = new Set(championsRegulationMBSpecies.map(toID));
const championsItemIds = new Set(championsItems.map(toID));
const championsMoveIds = new Set(championsMoves.map(toID));

export const isChampionsLegalSpeciesId = (id: string): boolean => championsSpeciesIds.has(toID(id));

export const isChampionsLegalItemId = (id: string): boolean => championsItemIds.has(toID(id));

export const isChampionsLegalMoveId = (id: string): boolean => championsMoveIds.has(toID(id));

/**
 * A Mega forme is never picked directly: a Pokémon Mega Evolves by holding its Mega Stone. The
 * formes are still part of the Champions dex so that stats and types can be looked up.
 */
export const isChampionsMegaForme = (species: { forme?: string; baseSpecies?: string }): boolean =>
  (species.forme ?? '').startsWith('Mega') && isChampionsLegalSpeciesId(species.baseSpecies ?? '');

const championsLearnsets = new Map<string, string[]>(Object.entries(championsLearnsetsBySpecies).map(([name, moves]) => [toID(name), moves.split(',')]));

/**
 * The moves a Pokémon may use in Champions.
 *
 * Champions does not share Gen 9's learnsets: it hands every Pokémon a single flat move pool that
 * both gives back moves Gen 9 had taken away (Charizard's Ancient Power, Gholdengo's Surf) and drops
 * moves Gen 9 still had (Incineroar's Knock Off, Grimmsnarl's Thunder Wave). The pool is complete on
 * its own - unlike a Showdown learnset it needs no egg moves or pre-evolution moves added to it.
 *
 * A Mega forme uses the move pool of the Pokémon that Mega Evolves into it.
 */
export const getChampionsLearnset = (species: { id: string; baseSpecies?: string }): string[] | undefined =>
  championsLearnsets.get(toID(species.id)) ?? championsLearnsets.get(toID(species.baseSpecies ?? ''));
